const hex = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, "A", "B", "C", "D", "E", "F"]; // array that has values to be used on changing the colors of the page

//#f15025 --- > This is the target value that needs to be generated # with 5 numbers attached to it

const btn = document.getElementById('btn'); //getting the btn on the page to be used on javascript
const color = document.querySelector('.color'); //getting the color property of the page to be used in javascript

btn.addEventListener('click', function(){ //once you click the button on the page, this function activates
let hexColor = '#'; // declaring the start of hexvalue with # using the hexColor variable
for (let i=0; i<6;i++){ // using for loop to generate the 5 number after the #
    hexColor += hex[getRandomNumber()]; //hexColor value # that will concatenate with the hex array value with the random number generated by the getRandomNumber function
}

color.textContent = hexColor; //changes the color of the body of HTML
document.body.style.backgroundColor = hexColor; //changes the value appearing on the page beside the word "Background Color"

})

//Generate Random Numbers between 0-15. 15 Because there are 16 values on the array 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, "A", "B", "C", "D", "E", "F"
//Array starts with index of 0
function getRandomNumber(){
    return Math.floor(Math.random() * hex.length)
//Math.floor function removes the decimals
//Math.random function generates random number 0 to less than 1 (inclusive of 0, but not 1) 
//Multiplied by the length of hex to have numbers between 0-15
}